<?php
/**
 * This source file is subject to the MIT license that is bundled with this package in the file LICENSE.txt.
 *
 * @package   Soliant\SimpleFM
 * @copyright Copyright (c) 2007-2013 Soliant Consulting, Inc. (http://www.soliantconsulting.com)
 * @author    jsmall@soliantconsulting.com
 */

namespace SoliantTest\SimpleFM;

use Soliant\SimpleFM\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-16 at 22:32:15.
 */
class AdapterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Adapter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Adapter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::setHostParams
     * @todo   Implement testSetHostParams().
     */
    public function testSetHostParams()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::setCredentials
     * @todo   Implement testSetCredentials().
     */
    public function testSetCredentials()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::setCallParams
     * @todo   Implement testSetCallParams().
     */
    public function testSetCallParams()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::getHostname
     * @todo   Implement testGetHostname().
     */
    public function testGetHostname()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::setHostname
     * @todo   Implement testSetHostname().
     */
    public function testSetHostname()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::getUsername
     * @todo   Implement testGetUsername().
     */
    public function testGetUsername()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::setUsername
     * @todo   Implement testSetUsername().
     */
    public function testSetUsername()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::setPassword
     * @todo   Implement testSetPassword().
     */
    public function testSetPassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::getDbname
     * @todo   Implement testGetDbname().
     */
    public function testGetDbname()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::setDbname
     * @todo   Implement testSetDbname().
     */
    public function testSetDbname()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::getLayoutname
     * @todo   Implement testGetLayoutname().
     */
    public function testGetLayoutname()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::setLayoutname
     * @todo   Implement testSetLayoutname().
     */
    public function testSetLayoutname()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::getCommandstring
     * @todo   Implement testGetCommandstring().
     */
    public function testGetCommandstring()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::getCommandarray
     * @todo   Implement testGetCommandarray().
     */
    public function testGetCommandarray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::setCommandstring
     * @todo   Implement testSetCommandstring().
     */
    public function testSetCommandstring()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::setCommandarray
     * @todo   Implement testSetCommandarray().
     */
    public function testSetCommandarray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::getProtocol
     * @todo   Implement testGetProtocol().
     */
    public function testGetProtocol()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::setProtocol
     * @todo   Implement testSetProtocol().
     */
    public function testSetProtocol()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::getPort
     * @todo   Implement testGetPort().
     */
    public function testGetPort()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::setPort
     * @todo   Implement testSetPort().
     */
    public function testSetPort()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::getFmresultsetUri
     * @todo   Implement testGetFmresultsetUri().
     */
    public function testGetFmresultsetUri()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::setFmresultsetUri
     * @todo   Implement testSetFmresultsetUri().
     */
    public function testSetFmresultsetUri()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::getFmpxmllayoutUri
     * @todo   Implement testGetFmpxmllayoutUri().
     */
    public function testGetFmpxmllayoutUri()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::setFmpxmllayoutUri
     * @todo   Implement testSetFmpxmllayoutUri().
     */
    public function testSetFmpxmllayoutUri()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::getRowsbyrecid
     * @todo   Implement testGetRowsbyrecid().
     */
    public function testGetRowsbyrecid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::setRowsbyrecid
     * @todo   Implement testSetRowsbyrecid().
     */
    public function testSetRowsbyrecid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::execute
     * @todo   Implement testExecute().
     */
    public function testExecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::displayXmlError
     * @todo   Implement testDisplayXmlError().
     */
    public function testDisplayXmlError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::extractErrorFromPhpMessage
     * @todo   Implement testExtractErrorFromPhpMessage().
     */
    public function testExtractErrorFromPhpMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Adapter::errorToEnglish
     * @todo   Implement testErrorToEnglish().
     */
    public function testErrorToEnglish()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
