<?php
namespace SoliantTest\SimpleFM\ZF2\Authentication\Adapter;

use Soliant\SimpleFM\ZF2\Authentication\Adapter\SimpleFM;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-28 at 11:20:49.
 */
class SimpleFMTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SimpleFM
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new SimpleFM;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Authentication\Adapter\SimpleFM::setUsername
     * @todo   Implement testSetUsername().
     */
    public function testSetUsername()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Authentication\Adapter\SimpleFM::setPassword
     * @todo   Implement testSetPassword().
     */
    public function testSetPassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Authentication\Adapter\SimpleFM::setRememberMe
     * @todo   Implement testSetRememberMe().
     */
    public function testSetRememberMe()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Authentication\Adapter\SimpleFM::getAccountNameField
     * @todo   Implement testGetAccountNameField().
     */
    public function testGetAccountNameField()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Authentication\Adapter\SimpleFM::authenticate
     * @todo   Implement testAuthenticate().
     */
    public function testAuthenticate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Authentication\Adapter\SimpleFM::escapeStringForFileMakerSearch
     * @todo   Implement testEscapeStringForFileMakerSearch().
     */
    public function testEscapeStringForFileMakerSearch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
