<?php
namespace SoliantTest\SimpleFM\ZF2\Authentication\Storage;

use Soliant\SimpleFM\ZF2\Authentication\Storage\Session;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-28 at 11:22:49.
 */
class SessionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Session
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Session;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Authentication\Storage\Session::setRememberMe
     * @todo   Implement testSetRememberMe().
     */
    public function testSetRememberMe()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Authentication\Storage\Session::forgetMe
     * @todo   Implement testForgetMe().
     */
    public function testForgetMe()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
