<?php
namespace Soliant\SimpleFM\ZF2;

use Soliant\SimpleFM\ZF2\AdapterServiceFactory;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-28 at 11:26:04.
 */
class AdapterServiceFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AdapterServiceFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AdapterServiceFactory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\AdapterServiceFactory::createService
     * @todo   Implement testCreateService().
     */
    public function testCreateService()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
