<?php
namespace SoliantTest\SimpleFM\ZF2\Authentication\Mapper;

use Soliant\SimpleFM\ZF2\Authentication\Mapper\Identity;
use Soliant\SimpleFM\ZF2\Authentication\Mapper\Exception\InvalidArgumentException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-28 at 11:22:22.
 */
class IdentityTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Identity
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Identity(
            'username',
            'password',
            true,
            null,
            ['simpleFMAdapterRowKey' => 'simpleFMAdapterRowValue']
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Authentication\Mapper\Identity::__construct
     * @covers Soliant\SimpleFM\ZF2\Authentication\Mapper\Identity::getIsLoggedIn
     * @covers Soliant\SimpleFM\ZF2\Authentication\Mapper\Identity::setIsLoggedIn
     * @covers Soliant\SimpleFM\ZF2\Authentication\Mapper\Identity::setArbitraryProperty
     * @covers Soliant\SimpleFM\ZF2\Authentication\Mapper\Identity::getUsername
     * @covers Soliant\SimpleFM\ZF2\Authentication\Mapper\Identity::setUsername
     */
    public function testGetsSets()
    {
        $this->object->setIsLoggedIn(true);
        $this->assertEquals(true, $this->object->getIsLoggedIn());
        $this->assertEquals('username', $this->object->getUsername());
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Authentication\Mapper\Identity::getPassword
     */
    public function testGetPassword()
    {
        $this->assertEquals(null, $this->object->getPassword(''));
        $this->assertEquals(null, $this->object->getPassword('fakeEncryptionKey'));
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Authentication\Mapper\Identity::setPassword
     */
    public function testSetPasswordBadEncryptionKey()
    {
        $this->setExpectedException(InvalidArgumentException::class);
        $this->object->setPassword('password', []);
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Authentication\Mapper\Identity::setPassword
     */
    public function testSetPasswordBadPassword()
    {
        $this->setExpectedException(InvalidArgumentException::class);
        $this->object->setPassword([], []);
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Authentication\Mapper\Identity::setPassword
     * @covers Soliant\SimpleFM\ZF2\Authentication\Mapper\Identity::getPassword
     * @todo   Implement testSetAndGetPasswordGood().
     * Requires mcrypt PHP extension
     */
    public function testSetAndGetPasswordGood()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
