<?php
namespace SoliantTest\SimpleFM\ZF2\Authentication\Mapper;

use Soliant\SimpleFM\ZF2\Authentication\Mapper\Identity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-28 at 11:22:22.
 */
class IdentityTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Identity
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Identity;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Authentication\Mapper\Identity::getIsLoggedIn
     * @todo   Implement testGetIsLoggedIn().
     */
    public function testGetIsLoggedIn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Authentication\Mapper\Identity::setIsLoggedIn
     * @todo   Implement testSetIsLoggedIn().
     */
    public function testSetIsLoggedIn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Authentication\Mapper\Identity::getUsername
     * @todo   Implement testGetUsername().
     */
    public function testGetUsername()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Authentication\Mapper\Identity::setUsername
     * @todo   Implement testSetUsername().
     */
    public function testSetUsername()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Authentication\Mapper\Identity::getPassword
     * @todo   Implement testGetPassword().
     */
    public function testGetPassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Authentication\Mapper\Identity::setPassword
     * @todo   Implement testSetPassword().
     */
    public function testSetPassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
