<?php
namespace SoliantTest\SimpleFM\Loader;

use Soliant\SimpleFM\Loader\FilePostContents;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-28 at 11:14:00.
 */
class FilePostContentsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FilePostContents
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FilePostContents;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Soliant\SimpleFM\Loader\FilePostContents::load
     * @todo   Implement testLoad().
     */
    public function testLoad()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
