<?php
namespace SoliantTest\SimpleFM\Loader;

use Soliant\SimpleFM\Loader\Mock;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-28 at 11:15:07.
 */
class MockTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Mock
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Mock;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Soliant\SimpleFM\Loader\Mock::getTestXml
     * @todo   Implement testGetTestXml().
     */
    public function testGetTestXml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Loader\Mock::setTestXml
     * @todo   Implement testSetTestXml().
     */
    public function testSetTestXml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Loader\Mock::load
     * @todo   Implement testLoad().
     */
    public function testLoad()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
