<?php
namespace SoliantTest\SimpleFM\Loader;

use Soliant\SimpleFM\Adapter;
use Soliant\SimpleFM\HostConnection;
use Soliant\SimpleFM\Loader\Mock as Loader;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-28 at 11:15:07.
 */
class MockTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Adapter
     */
    protected $adapter;

    /**
     * @var Loader
     */
    protected $loader;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $params = ['hostname' => 'localhost', 'dbname' => 'testdb', 'username' => 'Admin', 'password' => ''];
        $hostConnection = new HostConnection(
            $params['hostname'],
            $params['dbname'],
            $params['username'],
            $params['password']
        );
        $testXmlFile = file_get_contents(__DIR__ . '/../TestAssets/sample_fmresultset.xml');

        $this->adapter = new Adapter($hostConnection);
        $this->loader = new Loader($testXmlFile);
        $this->adapter->setLoader($this->loader);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Soliant\SimpleFM\Loader\Mock::__construct
     * @covers Soliant\SimpleFM\Loader\Mock::load
     * @covers Soliant\SimpleFM\Loader\Mock::setTestXml
     * @covers Soliant\SimpleFM\Loader\AbstractLoader::handleReturn
     * @covers Soliant\SimpleFM\Loader\AbstractLoader::errorCapture
     * @covers Soliant\SimpleFM\Loader\AbstractLoader::hasError
     */
    public function testLoad()
    {
        $this->loader->load();
        $this->assertInstanceOf(Loader::class, $this->loader);
    }

    /**
     * @covers Soliant\SimpleFM\Loader\Mock::__construct
     * @covers Soliant\SimpleFM\Loader\Mock::load
     * @covers Soliant\SimpleFM\Loader\Mock::setMockError
     * @covers Soliant\SimpleFM\Loader\AbstractLoader::handleReturn
     * @covers Soliant\SimpleFM\Loader\AbstractLoader::errorCapture
     * @covers Soliant\SimpleFM\Loader\AbstractLoader::hasError
     */
    public function testMockError()
    {
        $this->loader->setMockError(
            'file_get_contents(http://10.0.0.13:80/fmi/xml/fmresultset.xml) ' .
            '[function.file-get-contents]: failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized'
        );
        $this->loader->load();
        $this->assertInstanceOf(Loader::class, $this->loader);
        $this->assertEquals('HTTP', $this->loader->getLastErrorResultFmResultSet()->getErrorType());
        $this->assertEquals(401, $this->loader->getLastErrorResultFmResultSet()->getErrorCode());

    }
}
