<?php
namespace SoliantTest\SimpleFM\Loader;

use Soliant\SimpleFM\Loader\Mock as Loader;
use Soliant\SimpleFM\HostConnection;
use Soliant\SimpleFM\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-28 at 11:15:07.
 */
class MockTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Adapter
     */
    protected $adapter;

    /**
     * @var Loader
     */
    protected $loader;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $params=array('hostname'=>'localhost','dbname'=>'testdb','username'=>'Admin','password'=>'');
        $hostConnection = new HostConnection(
            $params['hostname'],
            $params['dbname'],
            $params['username'],
            $params['password']
        );
        $testXmlFile = file_get_contents(__DIR__ . '/../TestAssets/sample_fmresultset.xml');

        $this->adapter = new Adapter($hostConnection);
        $this->loader = new Loader($testXmlFile);
        $this->adapter->setLoader($this->loader);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Soliant\SimpleFM\Loader\Mock::__construct
     * @covers Soliant\SimpleFM\Loader\Mock::load
     * @covers Soliant\SimpleFM\Loader\Mock::setTestXml
     * @covers Soliant\SimpleFM\Loader\AbstractLoader::handleReturn
     */
    public function testLoad()
    {
        $this->loader->load();
        $this->assertInstanceOf(Loader::class, $this->loader);
    }
}
