<?php
namespace SoliantTest\SimpleFM\ZF2\Entity;

use Soliant\SimpleFM\ZF2\Entity\AbstractEntity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-28 at 11:25:01.
 */
class AbstractEntityTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AbstractEntity
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new AbstractEntity;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Entity\AbstractEntity::__toString
     * @todo   Implement test__toString().
     */
    public function testToString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Entity\AbstractEntity::getRecid
     * @todo   Implement testGetRecid().
     */
    public function testGetRecid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Entity\AbstractEntity::setRecid
     * @todo   Implement testSetRecid().
     */
    public function testSetRecid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Entity\AbstractEntity::getModid
     * @todo   Implement testGetModid().
     */
    public function testGetModid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Entity\AbstractEntity::setModid
     * @todo   Implement testSetModid().
     */
    public function testSetModid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Entity\AbstractEntity::getIsSerializable
     * @todo   Implement testGetIsSerializable().
     */
    public function testGetIsSerializable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Entity\AbstractEntity::setIsSerializable
     * @todo   Implement testSetIsSerializable().
     */
    public function testSetIsSerializable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Entity\AbstractEntity::getFieldMapMerged
     * @todo   Implement testGetFieldMapMerged().
     */
    public function testGetFieldMapMerged()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Entity\AbstractEntity::unserialize
     * @todo   Implement testUnserialize().
     */
    public function testUnserialize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Entity\AbstractEntity::serialize
     * @todo   Implement testSerialize().
     */
    public function testSerialize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Entity\AbstractEntity::getArrayCopy
     * @todo   Implement testGetArrayCopy().
     */
    public function testGetArrayCopy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Entity\AbstractEntity::toArray
     * @todo   Implement testToArray().
     */
    public function testToArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\ZF2\Entity\AbstractEntity::exchangeArray
     * @todo   Implement testExchangeArray().
     */
    public function testExchangeArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
