<?php
namespace SoliantTest\SimpleFM\Parser;

use Soliant\SimpleFM\Parser\AbstractParser;
use Soliant\SimpleFM\Result\FmResultSet;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-03 at 13:27:50.
 */
class AbstractParserTest extends \PHPUnit_Framework_TestCase
{
    protected $mockParser;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $xml = null;
        $commandUrlDebug = 'fakeUrl';
        $originalClassName = 'Soliant\SimpleFM\Parser\AbstractParser';
        $arguments = [$xml, $commandUrlDebug];
        $mockClassName = 'MockParser';
        $callOriginalConstructor = true;
        $callOriginalClone = true;
        $callAutoload = true;
        $mockedMethods = [
            'parse',
        ];
        $cloneArguments = false;
        $this->mockParser = $this->getMockForAbstractClass(
            $originalClassName,
            $arguments,
            $mockClassName,
            $callOriginalConstructor,
            $callOriginalClone,
            $callAutoload,
            $mockedMethods,
            $cloneArguments
        );
        $this->mockParser->expects($this->any())
            ->method('parse')
            ->will($this->returnValue('value'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Soliant\SimpleFM\Parser\AbstractParser::__construct
     * @covers Soliant\SimpleFM\Parser\AbstractParser::handleEmptyXml
     */
    public function testHandleEmptyXml()
    {
        $closure = function () {
            return $this->handleEmptyXml(FmResultSet::class);
        };

        $mockParserFunction = $closure->bindTo($this->mockParser, $this->mockParser);

        $result = $mockParserFunction();

        $this->assertInstanceOf(FmResultSet::class, $result);
    }

    /**
     * @covers Soliant\SimpleFM\Parser\AbstractParser::__construct
     * @covers Soliant\SimpleFM\Parser\AbstractParser::handleEmptyXml
     */
    public function testHandleEmptyXmlWrongClass()
    {
        $this->setExpectedException(\Soliant\SimpleFM\Exception\RuntimeException::class);
        $closure = function () {
            return $this->handleEmptyXml(\stdClass::class);
        };

        $mockParserFunction = $closure->bindTo($this->mockParser, $this->mockParser);

        $mockParserFunction();
    }

    /**
     * @covers Soliant\SimpleFM\Parser\AbstractParser::__construct
     * @covers Soliant\SimpleFM\Parser\AbstractParser::handleEmptyXml
     */
    public function testHandleEmptyXmlInvalidClass()
    {
        $this->setExpectedException(\Soliant\SimpleFM\Exception\RuntimeException::class);
        $closure = function () {
            return $this->handleEmptyXml('InvalidClassName');
        };

        $mockParserFunction = $closure->bindTo($this->mockParser, $this->mockParser);

        $mockParserFunction();
    }
}
