<?php
namespace SoliantTest\SimpleFM\Parser;

use Soliant\SimpleFM\Parser\FmResultSetParser;
use Soliant\SimpleFM\Result\FmResultSet;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-27 at 20:57:00.
 */
class FmResultSetParserTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FmResultSetParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $xml = file_get_contents(__DIR__ . '/../TestAssets/projectsampledata.xml');
        $commandDebugUrl = 'commandUrlDebug';
        $this->object = new FmResultSetParser($xml, $commandDebugUrl);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Soliant\SimpleFM\Parser\FmResultSetParser::setRowsByRecId
     * @covers Soliant\SimpleFM\Parser\FmResultSetParser::parse
     */
    public function testParseWithRowsByRecId()
    {
        $this->object->setRowsByRecId(true);
        $result = $this->object->parse('commandUrlDebug');
        $this->assertInstanceOf(FmResultSet::class, $result);
        $rows = $result->getRows();

        // First row is indexed as 7676
        $this->assertEquals($rows[7676], array_shift($rows));
    }

    /**
     * @covers Soliant\SimpleFM\Parser\FmResultSetParser::__construct
     * @covers Soliant\SimpleFM\Parser\FmResultSetParser::parse
     */
    public function testParseWithRowsByIndex()
    {
        $result = $this->object->parse('commandUrlDebug');
        $this->assertInstanceOf(FmResultSet::class, $result);
        $rows = $result->getRows();

        // First row is indexed as 0
        $this->assertEquals($rows[0], array_shift($rows));

        // Empty result
        $parser = new FmResultSetParser('');
        $result = $parser->parse('commandUrlDebug');
        $this->assertInstanceOf(FmResultSet::class, $result);
    }

    /**
     * @covers Soliant\SimpleFM\Parser\FmResultSetParser::parse
     * @todo test parse execution with 2 identical portals on the same layout
     */
    public function testParseWithNonUniquePortalsOnSameLayout()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Parser\FmResultSetParser::parse
     * @todo test parse execution with invalid field names
     */
    public function testParseWithInvalidFieldName()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
