<?php
namespace SoliantTest\SimpleFM\Parser;

use Soliant\SimpleFM\Parser\FmResultSetParser;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-27 at 20:57:00.
 */
class FmResultSetParserTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FmResultSetParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $xml = '';
        $commandDebugUrl = '';
        $this->object = new FmResultSetParser($xml, $commandDebugUrl);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Soliant\SimpleFM\Parser\FmResultSetParser::getRowsByRecId
     * @todo   Implement testGetRowsByRecId().
     */
    public function testGetRowsByRecId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Parser\FmResultSetParser::setRowsByRecId
     * @todo   Implement testSetRowsByRecId().
     */
    public function testSetRowsByRecId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Parser\FmResultSetParser::parse
     * @todo   Implement testParse().
     */
    public function testParse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Parser\FmResultSetParser::parse
     * @todo   Implement testParseWithIndexing().
     */
    public function testParseWithIndexing()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Parser\FmResultSetParser::parse
     * @todo test parse execution with 2 identical portals on the same layout
     */
    public function testParseWithNonUniquePortalsOnSameLayout()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Soliant\SimpleFM\Parser\FmResultSetParser::parse
     * @todo test parse execution with invalid field names
     */
    public function testParseWithInvalidFieldName()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
